SELECT * FROM JOBS;

SELECT SALARY  FROM DEVELOPERS;

SELECT MIN(SALARY) FROM TESTERS;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME , SALARY FROM EMPLOYEES;

SELECT COUNT(SALARY) FROM EMPLOYEES WHERE SALARY <= 5000;

SELECT COUNT(SALARY) FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 7000;

SELECT DISTINCT REGION_ID FROM COUNTRIES;

SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY <(SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES));

SELECT ROUND(AVG(SALARY),3) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT COUNT(DISTINCT DEPARTMENT_NAME) FROM DEPARTMENTS;

SELECT START_DATE FROM JOB_HISTORY ORDER BY START_DATE DESC;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%';

SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '%IT%';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(100,50,80);