SELECT SUBSTR(FIRST_NAME,0,1) || SUBSTR(LAST_NAME,0,1) AS "INITIALS",SALARY,JOB_ID FROM EMPLOYEES;

SELECT FIRST_NAME || LAST_NAME AS "FULLNAME", SALARY, PHONE_NUMBER, HIRE_DATE FROM EMPLOYEES;

SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES ORDER BY LENGTH(FIRST_NAME) DESC;

SELECT * FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) = ((SELECT MAX(LENGTH(FIRST_NAME)) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(60,90,100,120,130);

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN(60,90,100,120,130);

SELECT MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

SELECT COUNT(JOB_ID),AVG(SALARY) FROM EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY) > 7500;

SELECT COUNT(JOB_ID), JOB_ID FROM EMPLOYEES WHERE SALARY<5000 GROUP BY JOB_ID;

SELECT SUM(SALARY), JOB_ID FROM EMPLOYEES GROUP BY JOB_ID;

SELECT FIRST_NAME || LAST_NAME AS "FULLNAME", LOWER(EMAIL || '@GMAİL.COM') FROM EMPLOYEES;

SELECT STREET_ADDRESS || CITY || POSTAL_CODE || COUNTRY_ID AS "FULL_ADDRESS" FROM LOCATIONS;