SELECT AVG(SALARY), JOB_ID,COUNT(JOB_ID) FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG', 'SA_REP', 'FI_ACCOUNT', 'AD_VP') GROUP BY JOB_ID ;

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%a%a%';

SELECT COUNTRY_NAME,COUNTRY_ID,REGION_NAME,C.REGION_ID FROM COUNTRIES C JOIN REGIONS R ON C.REGION_ID = R.REGION_ID;

SELECT FIRST_NAME, LAST_NAME, D.DEPARTMENT_NAME, D.DEPARTMENT_ID FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE D.DEPARTMENT_ID IN (80,40);

SELECT FIRST_NAME, LAST_NAME ,D.DEPARTMENT_NAME, D.DEPARTMENT_ID FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME, LAST_NAME, D.DEPARTMENT_NAME, D.DEPARTMENT_ID FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;