SELECT UNIQUE SALARY FROM EMPLOYEES WHERE ROWNUM<10 ORDER BY SALARY DESC  ;

SELECT MIN(SALARY) FROM (SELECT UNIQUE SALARY FROM EMPLOYEES ORDER BY SALARY DESC)  WHERE ROWNUM < 4 ;

SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC ) WHERE ROWNUM < 15;

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC ) WHERE ROWNUM < 15);

SELECT MAX(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC) WHERE ROWNUM <6 ;

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC) WHERE ROWNUM <6);
