SELECT UNIQUE SALARY FROM EMPLOYEES WHERE ROWNUM<10 ORDER BY SALARY DESC  ;

SELECT CONCAT(FIRST_NAME, LAST_NAME) FULLNAME, D.DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY=(SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM<6);

SELECT MAX(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC);
